export default [
  {
    adult: false,
    backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: "en",
    original_title: "Free Guy",
    overview:
      "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
    popularity: 3870.583,
    poster_path: "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
    release_date: "2021-08-11",
    title: "Free Guy",
    video: false,
    vote_average: 7.9,
    vote_count: 1195,
  },
  {
    adult: false,
    backdrop_path: "/iTgM25ftE7YtFgZwUZupVp8A61S.jpg",
    genre_ids: [9648, 53, 27],
    id: 631843,
    original_language: "en",
    original_title: "Old",
    overview:
      "A group of families on a tropical holiday discover that the secluded beach where they are staying is somehow causing them to age rapidly – reducing their entire lives into a single day.",
    popularity: 2622.428,
    poster_path: "/vclShucpUmPhdAOmKgf3B3Z4POD.jpg",
    release_date: "2021-07-21",
    title: "Old",
    video: false,
    vote_average: 6.7,
    vote_count: 933,
  },
  {
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: "en",
    original_title: "Shang-Chi and the Legend of the Ten Rings",
    overview:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    popularity: 2330.572,
    poster_path: "/xeItgLK9qcafxbd8kYgv7XnMEog.jpg",
    release_date: "2021-09-01",
    title: "Shang-Chi and the Legend of the Ten Rings",
    video: false,
    vote_average: 7.8,
    vote_count: 1074,
  },
  {
    adult: false,
    backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
    genre_ids: [28, 12, 14, 35],
    id: 436969,
    original_language: "en",
    original_title: "The Suicide Squad",
    overview:
      "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
    popularity: 2223.745,
    poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
    release_date: "2021-07-28",
    title: "The Suicide Squad",
    video: false,
    vote_average: 7.9,
    vote_count: 4117,
  },
  {
    adult: false,
    backdrop_path: "/MDYanFolbT76dj0gsCbhS2GM5A.jpg",
    genre_ids: [37, 28],
    id: 859860,
    original_language: "en",
    original_title: "Catch the Bullet",
    overview:
      "U.S. marshal Britt MacMasters returns from a mission to find his father wounded and his son kidnapped by the outlaw Jed Blake. Hot on their trail, Britt forms a posse with a gunslinging deputy and a stoic Pawnee tracker. But Jed and Britt tread dangerously close to the Red Desert’s Sioux territory.",
    popularity: 2219.014,
    poster_path: "/qKxrBZ8Ts4KHZKp7BT6GAVMLFO2.jpg",
    release_date: "2021-09-10",
    title: "Catch the Bullet",
    video: false,
    vote_average: 6.1,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg",
    genre_ids: [28, 12],
    id: 568620,
    original_language: "en",
    original_title: "Snake Eyes: G.I. Joe Origins",
    overview:
      "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
    popularity: 2113.234,
    poster_path: "/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg",
    release_date: "2021-07-22",
    title: "Snake Eyes: G.I. Joe Origins",
    video: false,
    vote_average: 7,
    vote_count: 488,
  },
  {
    adult: false,
    backdrop_path: "/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg",
    genre_ids: [80, 53],
    id: 637534,
    original_language: "fr",
    original_title: "BAC Nord",
    overview:
      "A police brigade working in the dangerous northern neighborhoods of Marseille, where the level of crime is higher than anywhere else in France.",
    popularity: 2049.876,
    poster_path: "/nLanxl7Xhfbd5s8FxPy8jWZw4rv.jpg",
    release_date: "2021-08-18",
    title: "The Stronghold",
    video: false,
    vote_average: 7.9,
    vote_count: 311,
  },
  {
    adult: false,
    backdrop_path: "/byflnwPMumyvrCW9SfO5Miq3647.jpg",
    genre_ids: [28, 53],
    id: 597891,
    original_language: "en",
    original_title: "Kate",
    overview:
      "After she's irreversibly poisoned, a ruthless criminal operative has less than 24 hours to exact revenge on her enemies and in the process forms an unexpected bond with the daughter of one of her past victims.",
    popularity: 1758.15,
    poster_path: "/uJgdT1boTSP0dDIjdTgGleg71l4.jpg",
    release_date: "2021-09-10",
    title: "Kate",
    video: false,
    vote_average: 6.8,
    vote_count: 509,
  },
  {
    adult: false,
    backdrop_path: "/vD8oPUpDUZDTGI5IVofxrUjxxUO.jpg",
    genre_ids: [28, 53],
    id: 595743,
    original_language: "en",
    original_title: "SAS: Red Notice",
    overview:
      "An off-duty SAS soldier, Tom Buckingham, must thwart a terror attack on a train running through the Channel Tunnel. As the action escalates on the train, events transpire in the corridors of power that may make the difference as to whether Buckingham and the civilian passengers make it out of the tunnel alive.",
    popularity: 1729.946,
    poster_path: "/6Y9fl8tD1xtyUrOHV2MkCYTpzgi.jpg",
    release_date: "2021-08-11",
    title: "SAS: Red Notice",
    video: false,
    vote_average: 6,
    vote_count: 192,
  },
  {
    adult: false,
    backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
    genre_ids: [28, 12, 53, 878],
    id: 497698,
    original_language: "en",
    original_title: "Black Widow",
    overview:
      "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
    popularity: 1428.273,
    poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    release_date: "2021-07-07",
    title: "Black Widow",
    video: false,
    vote_average: 7.7,
    vote_count: 5176,
  },
  {
    adult: false,
    backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
    genre_ids: [12, 14, 35, 28],
    id: 451048,
    original_language: "en",
    original_title: "Jungle Cruise",
    overview:
      "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
    popularity: 1418.677,
    poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
    release_date: "2021-07-28",
    title: "Jungle Cruise",
    video: false,
    vote_average: 7.8,
    vote_count: 2742,
  },
  {
    adult: false,
    backdrop_path: "/nprqOIEfiMMQx16lgKeLf3rmPrR.jpg",
    genre_ids: [28],
    id: 619297,
    original_language: "en",
    original_title: "Sweet Girl",
    overview:
      "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
    popularity: 1257.258,
    poster_path: "/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
    release_date: "2021-08-18",
    title: "Sweet Girl",
    video: false,
    vote_average: 6.9,
    vote_count: 603,
  },
  {
    adult: false,
    backdrop_path: "/gzppdxEJ6fofhtLzSVSUJZEVxvq.jpg",
    genre_ids: [28, 878, 53],
    id: 848278,
    original_language: "en",
    original_title: "Jurassic Hunt",
    overview:
      "Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!",
    popularity: 1248.25,
    poster_path: "/bZnOioDq1ldaxKfUoj3DenHU7mp.jpg",
    release_date: "2021-09-01",
    title: "Jurassic Hunt",
    video: false,
    vote_average: 5.1,
    vote_count: 133,
  },
  {
    adult: false,
    backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
    genre_ids: [28, 80, 53],
    id: 385128,
    original_language: "en",
    original_title: "F9",
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 1175.336,
    poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
    release_date: "2021-05-19",
    title: "F9",
    video: false,
    vote_average: 7.5,
    vote_count: 3813,
  },
  {
    adult: false,
    backdrop_path: "/mtRW6eAwOO27h3zrfU2foQFW7Hg.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 675445,
    original_language: "en",
    original_title: "PAW Patrol: The Movie",
    overview:
      "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.",
    popularity: 1165.807,
    poster_path: "/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
    release_date: "2021-08-09",
    title: "PAW Patrol: The Movie",
    video: false,
    vote_average: 7.9,
    vote_count: 484,
  },
  {
    adult: false,
    backdrop_path: "/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg",
    genre_ids: [14, 12, 35],
    id: 589754,
    original_language: "ru",
    original_title: "Последний богатырь: Корень зла",
    overview:
      "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.",
    popularity: 1116.825,
    poster_path: "/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg",
    release_date: "2021-01-01",
    title: "The Last Warrior: Root of Evil",
    video: false,
    vote_average: 7.6,
    vote_count: 28,
  },
  {
    adult: false,
    backdrop_path: "/dsdbViTNjLu4DbgkkYmuY4xDQ20.jpg",
    genre_ids: [27, 53, 9648],
    id: 585216,
    original_language: "en",
    original_title: "Escape Room: Tournament of Champions",
    overview:
      "Six people unwittingly find themselves locked in another series of escape rooms, slowly uncovering what they have in common to survive as they discover all the games that they've played before.",
    popularity: 1104.718,
    poster_path: "/jGYJyPzVgrVV2bgClI9uvEZgVLE.jpg",
    release_date: "2021-07-01",
    title: "Escape Room: Tournament of Champions",
    video: false,
    vote_average: 7.1,
    vote_count: 437,
  },
  {
    adult: false,
    backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 508943,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    popularity: 1084.376,
    poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
    release_date: "2021-06-17",
    title: "Luca",
    video: false,
    vote_average: 8,
    vote_count: 4622,
  },
  {
    adult: false,
    backdrop_path: "/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: "en",
    original_title: "The Boss Baby: Family Business",
    overview:
      "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
    popularity: 1078.415,
    poster_path: "/uWStkK8bq9ixY3fc7y209ZleCoF.jpg",
    release_date: "2021-07-01",
    title: "The Boss Baby: Family Business",
    video: false,
    vote_average: 7.8,
    vote_count: 1425,
  },
  {
    adult: false,
    backdrop_path: "/8s4h9friP6Ci3adRGahHARVd76E.jpg",
    genre_ids: [16, 35, 10751, 878],
    id: 379686,
    original_language: "en",
    original_title: "Space Jam: A New Legacy",
    overview:
      "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
    popularity: 1065.044,
    poster_path: "/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
    release_date: "2021-07-08",
    title: "Space Jam: A New Legacy",
    video: false,
    vote_average: 7.4,
    vote_count: 2276,
  },
];
